### ISSUE TITLE
feat(nmrcraft/models): add more models

### ISSUE THREAD

**Issue by mlederbauer** [mlederbauer/NMRcraft#23]
Random Forest Classifier? Logistic Multivariate Reg? Decision Tree? Ensemble Model?

implement a hyperparameter optimization in `nmrcraft/models` accordingly

**Comment by tiaguinho-code** [comment]
I'll grab this issue and make a branch!

**Comment by mlederbauer** [comment]
for the future: add unit tests

**Comment by mlederbauer** [comment]
I am adding tests as soon as PR is merged into main
