### ISSUE TITLE
feat(nmrcraft and scripts): baseline experiments

### ISSUE THREAD

**Issue by mlederbauer** [mlederbauer/NMRcraft#24]
always min. 6 tensors as input
1st: 6 tensors -> metal category
2nd: 6 tensors -> E-ligand
3rd: 6 tensots -> metal, E-ligand category
4th:  6 tensors, metal, E-ligand, 5 ligands -> 6th ligand

generate for each of those tasks:
- plots and scores accuracy, ROC, ...
- different dataset sizes: 1%, 10%, 100%
- anything else?

**Comment by mlederbauer** [comment]
It would be fantastic to prioritize this to be able to get results until Friday
@wikicraft @mlederbauer @tiaguinho-code @strsamue @kbiniek

**Comment by mlederbauer** [comment]
We should be able to adapt the DataLoader class “dynamically” and then select the target and feature columns depending on which experiment we want to run see PR #31

**Comment by tiaguinho-code** [comment]
single target experiments should be doable now with the DataLoader. For multitarget experiments we still need to add onehot encoding, as the current dataset we get is categorical.

**Comment by mlederbauer** [comment]
idea: extrapolating by training on 6 coordinate, testing on 5-coordinate or vice versa

**Comment by mlederbauer** [comment]
1.) input: 6 NMR tensors, output: metal
2.) input: 6 NMR tensors, output: E-ligand
3.) input: 6 NMR tensors, output: X3-ligand
4.) input: 6 NMR tensors, output: metal & E-ligand
5.) input: 6 NMR tensors, output: metal & X3-ligand
6.) input: 6 NMR tensors, output: E-ligand & X3-ligand
7.) input: 6 NMR tensors, output: metal & E-ligand & X3-ligand

8.) input: 6 NMR tensors+all other ligands, output: metal
9.) input: 6 NMR tensors+all other ligands+metal, output: E-ligand
10.) input: 6 NMR tensors+all other ligands+metal, output: X3-ligand
11.) input: 6 NMR tensors+all other ligands, output: metal & E-ligand
12.) input: 6 NMR tensors+all other ligands, output: metal & X3-ligand
13.) input: 6 NMR tensors+all other ligands, output: E-ligand & X3-ligand
14.) input: 6 NMR tensors+all other ligands, output: metal & E-ligand & X3-ligand

those are quite a lot, I suggest to keep the following, what do you think?


Research Questons:
- Does more data = better results?
