### ISSUE TITLE
fix(DataLoader): fix one-hot encoding and implement tests for multiple cases -- metal as target, other metals, ...

### ISSUE THREAD

**Issue by mlederbauer** [mlederbauer/NMRcraft#36]
Also add a bit of documentations of "how to run tests" so that one can mitigate this earlier on in the development

**Comment by mlederbauer** [comment]
Will try to fix this now

**Comment by tiaguinho-code** [comment]
I'll get to work on the Tests for the dataloader to make sure this thing keeps working in the future
